esphome:
  name: air
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
# api:
  # password: !secret api_password

# web_server:
  # port: 80

ota:

mqtt:   
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: air

uart:
  rx_pin: 3
  baud_rate: 9600

i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

sensor:
  - platform: wifi_signal
    name: "wifi"
    update_interval: 60s

  - platform: bme280
    temperature:
      name: "temperature"
      oversampling: 16x
    pressure:
      name: "pressure"
    humidity:
      name: "humidity"
      oversampling: 16x
    address: 0x76
    update_interval: 10s
  
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "pm1"
      filters:
      - throttle: 15s
      - heartbeat: 60s
      # - debounce: 30s
      - delta: 2.0
    pm_2_5:
      name: "pm2.5"
      filters:
      - throttle: 15s
      - heartbeat: 60s
      # - debounce: 30s
      - delta: 2.0
    pm_10_0:
      name: "pm10"
      filters:
        - throttle: 15s
        - heartbeat: 60s
        # - debounce: 30s
        - delta: 2.0
