esphome:
  name: dev
  # platform: ESP8266
  # board: d1_mini
  # platform: ESP8266
  # board: esp01_1m
  platform: ESP32
  board: nodemcu-32s
  includes:
    #   - mux_sensor.h
    - SSD1327.h
  libraries:
    - U8g2
  #   - CD74HC4067

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: heat_up.local

api:
  password: !secret api_password

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
# api:

ota:

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: test/dev

# binary_sensor:
# - platform: custom
#   lambda: |-
#     auto muxSensor = new MuxSensor();
#     App.register_component(muxSensor);
#     return {muxSensor};

#   binary_sensors:
#     name: "My Mux Sensor"

# binary_sensor:
#   - platform: gpio
#     name: "s"
#     pin:
#       number: GPIO14
#       inverted: True
#       mode: INPUT_PULLUP
# switch:
#   - platform: gpio
#     pin: GPIO13
#     name: "r"
#     inverted: true

sensor:
  - platform: wifi_signal
    name: 'WiFi Signal Sensor'
    update_interval: 5s

i2c:    
  sda: D21
  scl: D22

custom_component:
  - lambda: |-
      auto my_custom = new SSD1327();
      return {my_custom};

# DC MOTOR:
# light:
#   - platform: monochromatic
#     name: "Motor1"
#     output: output_component1
#   - platform: monochromatic
#     name: "Motor2"
#     output: output_component2

# output:
#   - platform: esp8266_pwm
#     id: output_component1
#     pin: D6
#   - platform: esp8266_pwm
#     id: output_component2
#     pin: D7
