esphome:
  name: e_entrance
  platform: ESP8266
  board: nodemcuv2
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  # esp8266_store_log_strings_in_flash: False

ota:

i2c:
  id: i2ccomponent

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
    return {ape_component};

mqtt:   
  broker: !secret mqtt_ip
  discovery: false
  topic_prefix: e/entrance

binary_sensor:
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 11),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 14),
              ape_binary_sensor(ape, 15),
              ape_binary_sensor(ape, 16),
              ape_binary_sensor(ape, 17)};
    binary_sensors:
      - name: "S1"
        filters:
          - invert:
      - name: "S2"
        filters:
          - invert:
      - name: "S3"
        filters:
          - invert:
      - name: "S4"
        filters:
          - invert:
      - name: "S5"
        filters:
          - invert:
      - name: "S6"
        filters:
          - invert:
      - name: "S7"
        filters:
          - invert:
      - name: "S8"
        filters:
          - invert:

switch:
- platform: custom
  lambda: |-
    return {ape_switch(ape, 2),
            ape_switch(ape, 3),
            ape_switch(ape, 4),
            ape_switch(ape, 5)
    };
  switches:
  - name: "R1"
    inverted: true
  - name: "R2"
    inverted: true
  - name: "R3"
    inverted: true
  - name: "R4"
    inverted: true
