esphome:
  name: e_entrance
  platform: ESP8266
  board: nodemcuv2
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  # esp8266_store_log_strings_in_flash: False

ota:
  password: !secret ota_password

api:
  password: !secret api_password

i2c:
  id: i2ccomponent

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
      return {ape_component};

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: e/entrance

binary_sensor:
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 11),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 14),
              ape_binary_sensor(ape, 15),
              ape_binary_sensor(ape, 16),
              ape_binary_sensor(ape, 17)};
    binary_sensors:
      - name: S1
        filters:
          - invert:
      - name: bath1
        filters:
          - invert:
        on_state:
          - switch.toggle: bath
      - name: S3
        filters:
          - invert:
      - name: entrance1
        filters:
          - invert:
        on_state:
          - switch.toggle: stairs
      - name: S5
        filters:
          - invert:
      - name: S6
        filters:
          - invert:
      - name: stairs
        filters:
          - invert:
        on_state:
          - switch.toggle: stairs
      - name: S8
        filters:
          - invert:

switch:
  - platform: custom
    lambda: |-
      return {ape_switch(ape, 2),
              ape_switch(ape, 3),
              ape_switch(ape, 4),
              ape_switch(ape, 5)
      };
    switches:
      - name: R1
        id: R1
        inverted: true
      - name: R2
        id: R2
        inverted: true
      - name: stairs
        id: stairs
        inverted: true
      - name: bath
        id: bath
        inverted: true
