esphome:
  name: heat_down
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  
logger:
  level: DEBUG

ota:

mqtt:   
  broker: !secret mqtt_ip
  discovery: false
  topic_prefix: heat/down

switch:
  - platform: gpio
    pin: 5
    name: "1"
    inverted: true
  - platform: gpio
    pin: 4
    name: "2"
    inverted: true