esphome:
  name: heat_down
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: heat_down.local

web_server:
  port: 80

api:
  password: !secret api_password

logger:
  level: DEBUG
  baud_rate: 0

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: heat/down

switch:
  # 1 - heat
  - platform: gpio
    pin: D4
    name: 'centrala'
    inverted: true
  # 2 - pump
  - platform: gpio
    pin: D3
    name: 'pompa'
    inverted: true
  # 4 - Living 1
  - platform: gpio
    pin: D1
    name: 'living1'
    inverted: true
  # 5 - living 2
  - platform: gpio
    pin: D0
    name: 'living2'
    inverted: true
  # 3 - birou
  - platform: gpio
    pin: D2
    name: 'birou'
    inverted: true
  # 6 - Dorm
  - platform: gpio
    pin: D5
    name: 'dormitor'
    inverted: true
  # 7 - baie
  - platform: gpio
    pin: D6
    name: 'baie'
    inverted: true
  # 8 - hol
  - platform: gpio
    pin: D7
    name: 'intrare'
    inverted: true
