esphome:
  name: heat_up
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 192.168.1.143

web_server:
  port: 80

# api:
#   password: !secret api_password

logger:
  level: DEBUG
  baud_rate: 0

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: heat/up

switch:
  # 1 Pompa
  - platform: gpio
    pin: D7
    name: 'pompa'
    inverted: true
  # 2 Maria 1
  - platform: gpio
    pin: D6
    name: 'maria1'
    inverted: true
  # 3 Maria 2
  - platform: gpio
    pin: D5
    name: 'maria2'
    inverted: true
  # 4 Baie hol
  - platform: gpio
    pin: D0
    name: 'baieHol'
    inverted: true
  # 5 Hol
  - platform: gpio
    pin: D3
    name: 'hol'
    inverted: true
  # 6 Baie Mat
  - platform: gpio
    pin: D2
    name: 'baieMatrimonial'
    inverted: true
  # 7 Dormitor Velux
  - platform: gpio
    pin: D1
    name: 'velux'
    inverted: true
  # 8 Dormitor Matrimonial
  - platform: gpio
    pin: D4
    name: 'matrimonial'
    inverted: true
