esphome:
  name: e_kitchen
  platform: ESP8266
  board: esp01_1m
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  # esp8266_store_log_strings_in_flash: False

ota:
  password: !secret ota_password

# api:
  # password: !secret api_password

i2c:
  id: i2ccomponent

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
      return {ape_component};

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: e/kitchen

binary_sensor:
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 11),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 14),
              ape_binary_sensor(ape, 15),
              ape_binary_sensor(ape, 16),
              ape_binary_sensor(ape, 17)};
    binary_sensors:
      - name: hall_middle
        filters:
          - invert:
        on_state:
          - switch.toggle: living
      - name: hall_left
        filters:
          - invert:
        on_state:
          - switch.toggle: kitchen
      - name: kitchen_left
        filters:
          - invert:
        on_state:
          - switch.toggle: kitchen
      - name: kitchen_right
        filters:
          - invert:
        on_state:
          - switch.toggle: table
      - name: kitchen_middle
        filters:
          - invert:
        on_state:
          - switch.toggle: living
      - name: hall_right
        filters:
          - invert:
        on_state:
          - switch.toggle: table

switch:
  - platform: custom
    lambda: |-
      return {ape_switch(ape, 2),
              ape_switch(ape, 3),
              ape_switch(ape, 4),
              ape_switch(ape, 5)
      };
    switches:
      - name: table
        id: table
        inverted: true
      - name: R2
        id: R2
        inverted: true
      - name: living
        id: living
        inverted: true
      - name: kitchen
        id: kitchen
        inverted: true
