esphome:
  name: e_living
  platform: ESP8266
  board: nodemcuv2
  includes:
    - ape.h
    - MuxSensor.h
  libraries:
    - CD74HC4067

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  # esp8266_store_log_strings_in_flash: False

ota:

i2c:
  id: i2ccomponent

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
    return {ape_component};

mqtt:   
  broker: 192.168.1.10
  discovery: false
  topic_prefix: e/living

binary_sensor:
- platform: custom
  lambda: |-
    // int pins[4] = {14, 12, 13, 15};
    // int channels[8] = {0, 2, 4, 6, 8, 10, 12, 14};
    // MuxSensor *muxSensor = new MuxSensor(pins, 2, channels);
    auto muxSensor = new MuxSensor();
    App.register_component(muxSensor);
    return {
      muxSensor->sensors[0],
      muxSensor->sensors[1],
      muxSensor->sensors[2],
      muxSensor->sensors[3],
      muxSensor->sensors[4],
      muxSensor->sensors[5],
      muxSensor->sensors[6],
      muxSensor->sensors[7],
    };
  binary_sensors:
  - name: "S1"
    filters:
      - invert:
  - name: "S2"
    filters:
      - invert:
  - name: "living_left"
    filters:
      - invert:
  - name: "living_right"
    filters:
      - invert:
  - name: "leftDoor_right"
    filters:
      - invert:
  - name: "living_up"
    filters:
      - invert:
  - name: "left_door_left"
    filters:
      - invert:
  - name: "living_down"
    filters:
      - invert:


switch:
- platform: custom
  lambda: |-
    return {ape_switch(ape, 5),
            ape_switch(ape, 6),
            ape_switch(ape, 7),
            ape_switch(ape, 8),
            ape_switch(ape, 9),
            ape_switch(ape, 10),
            ape_switch(ape, 11),
            ape_switch(ape, 12)
    };
  switches:
  - name: "R1"
    inverted: true
  - name: "living"
    inverted: true
  - name: "R3"
    inverted: true
  - name: "R4"
    inverted: true
  - name: "R5"
    inverted: true
  - name: "wall_left"
    inverted: true
  - name: "R7"
    inverted: true
  - name: "R8"
    inverted: true
