esphome:
  name: e_office
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

ota:

mqtt:   
  broker: !secret mqtt_ip
  discovery: false
  topic_prefix: e/office

binary_sensor:
  - platform: gpio
    name: "office"
    pin:
      number: D5
      inverted: True
      mode: INPUT_PULLUP
  - platform: gpio
    name: "tech"
    pin:
      number: D6
      inverted: True
      mode: INPUT_PULLUP
# TODO Make a backup when no mqtt connection, 
# automatically turn on on binary_sensor change
switch:
  - platform: gpio
    pin: D7
    name: "office"
    inverted: true
  - platform: gpio
    pin: D8
    name: "tech"
    inverted: true
