esphome:
  name: e_office
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

ota:

api:
  password: !secret api_password

mqtt:   
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: e/office

binary_sensor:
  - platform: gpio
    name: "office"
    pin:
      number: D5
      inverted: True
      mode: INPUT_PULLUP
    on_state:
      # then: # Automation should always be here...
      #   if:
      #     condition:
      #       mqtt.connected:
      #     else:
      - switch.toggle: office
  - platform: gpio
    name: "tech"
    pin:
      number: D6
      inverted: True
      mode: INPUT_PULLUP
    on_state:
      # then:
      #   if:
      #     condition:
      #       mqtt.connected:
      #     else:
      - switch.toggle: tech
switch:
  - platform: gpio
    pin: D7
    name: "office"
    id: "office"
    inverted: true
  - platform: gpio
    pin: D8
    name: "tech"
    id: "tech"
    inverted: true
