esphome:
  name: first
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

mqtt:   
  broker: 192.168.1.10
  discovery: false
  topic_prefix: electric/office

binary_sensor:
  - platform: gpio
    name: "switch1"
    pin:
      number: D5
      inverted: True
      mode: INPUT_PULLUP
  - platform: gpio
    name: "switch2"
    pin:
      number: D6
      inverted: True
      mode: INPUT_PULLUP
# TODO Make a backup when no mqtt connection, 
# automatically turn on on binary_sensor change
switch:
  - platform: gpio
    pin: D7
    name: "relay1"
    inverted: true
  - platform: gpio
    pin: D8
    name: "relay2"
    inverted: true
