esphome:
  name: power
  # platform: ESP32
  # board: nodemcu-32s
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
# api:
  # password: !secret api_password

# web_server:
  # port: 80

ota:

mqtt:   
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: power

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  # stop_bits: 2

sensor:
  - platform: pzemac
    current:
      name: "current"
    voltage:
      name: "voltage"
    power:
      name: "power"
    frequency:
      name: "frequency"
    energy:
      name: "energy"
    power_factor:
      name: "power-factor"
    update_interval: 1s
