esphome:
  name: rcdump
  # platform: ESP8266
  # board: d1_mini_lite
  platform: ESP32
  board: nodemcu-32s
  # platform: ESP8266
  # board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: air.local

# Enable logging
logger:
  # baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
# api:
#   password: !secret api_password

# web_server:
# port: 80

ota:

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: rcdump

remote_receiver:
  # pin: 14
  pin: GPIO25
  dump:
    - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
# remote_transmitter:
#   # pin: 5
#   pin: GPIO26
#   carrier_duty_percent: 50%
# switch:
#   - platform: template
#     name: Aux Bluetooth
#     turn_on_action:
#       - remote_transmitter.transmit_raw:
#           code:
#             [
#               -983,
#               1504,
#               -488,
#               507,
#               -487,
#               504,
#               -490,
#               508,
#               -491,
#               504,
#               -496,
#               1494,
#               -493,
#               1496,
#               -487,
#               1502,
#               -487,
#               1502,
#               -486,
#               1503,
#               -487,
#               1502,
#               -489,
#               1500,
#               -486,
#               1502,
#               -488,
#               507,
#               -490,
#               500,
#               -492,
#               507,
#               -488,
#               507,
#               -489,
#             ]
