esphome:
  name: rolls
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  password: !secret api_password

# web_server:
# port: 80

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: rolls

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Button 1"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Button 2"
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Button 3"
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Button 4"
  - platform: status
    name: "Sonoff 4CH Status"

switch:
  - platform: gpio
    id: relay1
    name: "window_up"
    pin: GPIO12
    interlock: [relay2]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay2
    name: "window_down"
    pin: GPIO5
    interlock: [relay1]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay3
    name: "door_up"
    pin: GPIO4
    interlock: [relay4]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay4
    name: "door_down"
    pin: GPIO15
    interlock: [relay3]
    restore_mode: ALWAYS_OFF
  # - platform: gpio
  #   id: relay5
  #   name: "s5"
  #   pin: GPIO01
  #   interlock: [relay6]
  #   restore_mode: ALWAYS_OFF
  #   inverted: true
  # - platform: gpio
  #   id: relay6
  #   name: "s6"
  #   pin: GPIO3
  #   interlock: [relay5]
  #   restore_mode: ALWAYS_OFF
  #   inverted: true
