esphome:
  name: test_esp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  
logger:
  level: DEBUG
  baud_rate: 0

ota:

mqtt:   
  broker: !secret mqtt_ip
  discovery: false
  topic_prefix: heat/up
