esphome:
  name: water_big
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  password: !secret api_password

# web_server:
# port: 80

ota:

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: water-big

switch:
  - platform: gpio
    id: relay1
    name: "middle-front"
    pin: GPIO32
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay2
    name: "alley"
    pin: GPIO33
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay3
    name: "middle-side"
    pin: GPIO22
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay4
    name: "hill"
    pin: GPIO26
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay5
    name: "front"
    pin: GPIO27
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay6
    name: "contour"
    pin: GPIO14
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay7
    name: "garage"
    pin: GPIO23
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay8
    name: "s8"
    pin: GPIO25
    inverted: true
    restore_mode: ALWAYS_OFF
