esphome:
  name: water_small
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  password: !secret api_password

# web_server:
# port: 80

ota:

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  topic_prefix: water-small

switch:
  - platform: gpio
    id: relay1
    name: "vegetables"
    pin: GPIO12
    interlock: [relay1, relay2, relay3, relay4]
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay2
    name: "behind-hill"
    pin: GPIO13
    interlock: [relay1, relay2, relay3, relay4]
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay3
    name: "back"
    pin: GPIO14
    interlock: [relay1, relay2, relay3, relay4]
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay4
    name: "middle-back"
    pin: GPIO2
    interlock: [relay1, relay2, relay3, relay4]
    inverted: true
    restore_mode: ALWAYS_OFF
