esphome:
  name: water
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret neighbour_wifi_ssid
  password: !secret neighbour_wifi_password
  # use_address: rcdump.local

# Enable logging
logger:
  baud_rate: 0
  # level: DEBUG
  # esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
# api:
#   password: !secret api_password

# web_server:
# port: 80

ota:
  password: !secret ota_password

mqtt:
  broker: !secret public_mqtt_ip
  username: !secret public_mqtt_user
  password: !secret public_mqtt_password
  discovery: false
  topic_prefix: water-25

switch:
  - platform: gpio
    id: relay1
    name: "4"
    pin: GPIO32
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay2
    name: "5"
    pin: GPIO33
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay3
    name: "3"
    pin: GPIO22
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay4
    name: "6"
    pin: GPIO26
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay5
    name: "8"
    pin: GPIO27
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay6
    name: "1"
    pin: GPIO14
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay7
    name: "2"
    pin: GPIO23
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: relay8
    name: "7"
    pin: GPIO25
    inverted: true
    interlock: [relay1, relay2, relay3, relay4, relay5, relay6, relay7, relay8]
    restore_mode: ALWAYS_OFF
